  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ITEM_V" ("ID", "ITEM_NAME", "UOM", "PUR_RATE", "SAL_RATE") AS 
  SELECT ID,
ITEM_NAME,
(SELECT UNIT_NAME FROM UOM WHERE ID=UOM) UNIT,
PUR_RATE,
SAL_RATE
FROM ITEM_MST
WHERE ACTIVE=1;
